FROM ubuntu:18.04

RUN  apt-get update
RUN  apt-get -y install golang-go go-dep git


RUN mkdir -p /go/src/github.com/lamarios/trsl8
WORKDIR /go/src/github.com/lamarios/trsl8

ADD api ./
ADD dao ./
ADD fileHandlers ./
ADD git ./
ADD utils ./

ADD main.go ./
ADD Gopkg.toml ./
ADD Gopkg.lock ./

RUN ls /go/src/github.com/lamarios/trsl8

ENV GOPATH /go
CMD dep ensure && go build -o trsl8
